In [11]:
import numpy as np
a=np.array([[1,2,3],[2,2,3]])
for _ in range(0):
    a=np.row_stack((a[0],a))
a

array([[1, 2, 3],
       [2, 2, 3]])

In [1]:
[1]+[2]

[1, 2]

In [18]:
import numpy as np
data=np.array([[1,2,3],[2,3,4]]).astype("uint8")
image_shape = data[0].shape

base_image = np.ones(image_shape).astype("uint8")
print([base_image] + data)

[[2 3 4]
 [3 4 5]]
